### ISSUE TITLE
How to filter datatype array and object?

### ISSUE THREAD

**Issue by wideweide** [ujjwalguptaofficial/JsStore#127]
table peope:object column such wife,array column like chilren
{id:1,wife:{name:Lily,age:36},children:[{name:tom,age:4},{name:hellen,age:6}]}
select * from people where wife.name='Lily' ?
select * from people where children.name='tom'
Is jsstore can do this and how to write the where :
con.select({
from: 'people',
where: {
wife.name: 'Lily',
children.name:'Tom'
}
})

**Comment by wideweide** [comment]
change the children's property to index? 
such as ： 
  wife_name => wife.name
  children_name => children.name ,['tom','hellen']

**Comment by wideweide** [comment]
maybe:
columns:{
 wife.name:{keyPath: [wift.nname]}, // if obj,just save Lily
 chilren.name: ｛keyPath:[children.name]｝// if array,save ['tom','hellen']
}
when insert data,just change to index

In this way, may support nested query

Perhaps,elasticsearch just doing like this... I am not sure...

**Comment by ujjwalguptaofficial** [comment]
This is achievable but not through indexeddb api. IndexedDb does not provide multi level indexing, so jsstore will have to loop through every data & check different property , compare value which will make all query very slow. 

I am really against doing it since indexeddb is a client side database which means a client can be a low spec device like mobile etc. 

In this case - the best option is to use join since join does operation on already filtered data.

As soon as indexedDb provides multi level indexing , feel free to reopen this issue.
