### ISSUE TITLE
Id duplicates on array insert, method to get current id var

### ISSUE THREAD

**Issue by DoktorD96** [ujjwalguptaofficial/JsStore#131]
http://jsstore.net/tutorial/export-json/

This doesn't work, but that's not an issue because the implementation is fairly easy just maybe you can remove it from the doc until it's ready.

Is there any method for getting current increment value without using the plain indexDB?
https://i.ibb.co/qn2hv7y/image.png

BTW so far awesome work.

**Comment by ujjwalguptaofficial** [comment]
Thanks Man

We have removed the exportJson, but seems like you found it from somewhere.

Regarding getting the stored incremental value, you can get the value when inserting data. You will have to specify return : true . Don't use those meta data value, they are not for users . 

So when you insert data with having return:true, it returns the actual data inserted instead of no of records inserted.

Check out the insert doc - http://jsstore.net/tutorial/insert/
