### ISSUE TITLE
Multiple Row Returned when querying ignoreCase on string data type 

### ISSUE THREAD

**Issue by tanjooxiang** [ujjwalguptaofficial/JsStore#174]
Multiple Row Returned querying with IgnoreCase True

Hello, 

I upgrade and used the latest version of JsStore 3.9.3 but is having issue with the ignoreCase parameter.

`select({
    from: "Customers",
    ignoreCase: true, 
    where: {
        customerName: 'Alfreds Futterkiste'
    }
});`

I tried the above code in the IDBstudio, but it return my 2 rows of data and the querying speed is much slower. I have also tested with other data that have consecutive alphabet or number and it seem to be returning multiple row too.  e.g 
Alfreds0000 produce 8 rows 

May I know why? Or is it Im doing it wrong where i shouldnt query it this way. 

Thank you.

**Comment by ujjwalguptaofficial** [comment]
@tanjooxiang no, you are not doing anything wrong. Actually i found that ignoreCase is very heavy - it generates all the possible combination of word and use `in` query. 

In your case -  due to heavy query something is not working properly. I am going to remove ignore case support. 

The solution is - to use regex : https://jsstore.net/tutorial/regex/

**Comment by ujjwalguptaofficial** [comment]
@tanjooxiang removed in v - 3.10.0 . Let me know if you have any question.

**Comment by tanjooxiang** [comment]
Okay noted. Thank for the work around!
