### ISSUE TITLE
Is there some way to encrypt data

### ISSUE THREAD

**Issue by xland** [ujjwalguptaofficial/JsStore#183]
# Title
Is there some way to encrypt the data

# Description 
Is there some way to encrypt the data
```js
const dataBase: IDataBase = {
        name: dbname,
        tables: [tblStudent],
        encrypt: true    //like this,   "dex" or "rsa"
};
```

**Comment by ujjwalguptaofficial** [comment]
no JsStore does not provide anything to do data processing but i have plan to solve this issue by creating plugins support in jsstore. 

I am thinking about adding middleware. So every api call be passed to series of middleware which can modify the inputs and finally will be passed to api. This way user can add common code & convert code into plugins.

Let me know if you have any suggestion. I will create it by end of week.

**Comment by ujjwalguptaofficial** [comment]
@xland i have added support for middleware & plugin in version - 3.11.1.

Here are doc link - 

* Middleware - https://jsstore.net/tutorial/middleware/
* Plugin - https://jsstore.net/tutorial/plugin

Using middleware you can encrypt data or decrypt data. So encrypting while inserting and decrypting while selecting.

If you have some time, i will request you to create a plugin and npm it so that other users also can take advantage of yours work :).

Let me know if need my help.

**Comment by xland** [comment]
Sorry, I can not contribute for that plugin now, Maybe some days later.
Thanks very much.

**Comment by ujjwalguptaofficial** [comment]
I have created a plugin `jsstore-encrypt`. It lets you store data in encrypted form with your own encryption method. Check the repo here - https://github.com/ujjwalguptaofficial/jsstore-encrypt

If you want any improvement or have any suggestion, feel free to raise issue on the `jsstore-encrypt` repo.
