### ISSUE TITLE
Unexpected behaviour of connection Class

### ISSUE THREAD

**Issue by marharyta** [ujjwalguptaofficial/JsStore#186]
# Having issues understanding the logic behind connection functionality, is there a possibility promises return wrong answers?

# Description 

I have pasted my original code in this Gist:
https://gist.github.com/marharyta/5ba57fdbe19ec5b5c7ae5f17185ec6ce

This is what happens in the console:

<img width="701" alt="Screenshot 2020-11-08 at 13 48 21" src="https://user-images.githubusercontent.com/7344718/98464095-133f7100-21c9-11eb-81fe-9c067004244e.png">

InitDb and OpenDb return false, yet the insert and select still seem to work. Is that expected?
I bit more documentation on the expected behaviour would be nice. 
I have pasted the last versions of the libarary locally, if that helps:
```
<script src="js/static/jsstore.js"></script> <script src="js/static/jsstore.worker.js"></script>
````

**Comment by ujjwalguptaofficial** [comment]
initDb & openDb return false because you have already initiated db earlier. Try in incognito & you will see value of initDb true.

Here is screenshot when i tried

![Screenshot from 2020-11-12 10-44-10](https://user-images.githubusercontent.com/10938615/98898941-af70bd00-24d4-11eb-9bcc-f31f1507abe7.png)

Let me know if there is any more doubt.
