### ISSUE TITLE
Bundle jsStore.js and jsStore.worker.js in one file

### ISSUE THREAD

**Issue by nielsnl68** [ujjwalguptaofficial/JsStore#222]
## Summary

I want to include all js files inside one package and send it to the browser.

Is that possible for `jsStore.js` and `jsStore.worker.js` and when so how do i link them together?

For instance how do i change `let jsstoreCon = new JsStore.Connection(new Worker("jsstore.worker.js"));`

when the loaded js file is named `main.js`

thanks and keep up the good work.

### Motivation

I want the user to see as less as possible. And want to block loading main.js when it is not loaded from within main `index.html`.

**Comment by ujjwalguptaofficial** [comment]
The reason i had to make two seperate files is because `Worker` requires seperate file - https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Using_web_workers .

You can bundle it together, then you have two options - 

* Execute code without worker - which will have performance issue
* Create your own worker and use bundle but you will have to manage the communication between worker and main script.

**Comment by nielsnl68** [comment]
okey, when you say so, then i skip that idea for now.  That's second option is not what i prepare to do right now. 

Just wondering if #221 was related to what i was asking.. i assume  not is it?


When you see an better solution in the future, please let me know. For now, i see it as not possible.

**Comment by ujjwalguptaofficial** [comment]
yes 221 was regarding using second option. but its not clear how they are using it.
