### ISSUE TITLE
Feature - Update setting value by calculation with other columns

### ISSUE THREAD

**Issue by ujjwalguptaofficial** [ujjwalguptaofficial/JsStore#231]
### Discussed in https://github.com/ujjwalguptaofficial/JsStore/discussions/230

<div type='discussions-op-text'>

<sup>Originally posted by **10787** June 28, 2021</sup>
Is it possible to set a value in an update operation, by referencing other columns, similar to the following sql example:
update orderLine
set lineAmount = price * qty

What would be the syntax in jsstore?
Not this for sure...:
        var noOfRowsUpdated = await jsstoreCon.update({
          in: 'orderLine',
          set: {
            lineAmount: 'quantityLine' * 'price'
          }
      });

Thanks</div>

**Comment by ujjwalguptaofficial** [comment]
`mapSet` feature has been added in v - 4.3.0. Here is doc - https://jsstore.net/tutorial/update/map-set/

**Comment by 10787** [comment]
hi, that was fast:-) I have tried testing the new mapSet feature, but I can't seem to get it activated. Below code (slightly simplified for the purpose of example) keeps updating lineAmount with value 0, instead of the calculation in the mapSet. Anything I can have missed?

You write a hint about storing the mapSet part in separat js file, but I don't have that option and prefer t just have it directly in the code. I hope that is not a problem?

Example:
//Prepare mapSet function for subsequent update statement
var lineAmountMapSet = {
    mapSet(setValue, storedValue) {
        setValue.lineAmount = storedValue.quantityLine * 12.34
    }
}
//Update order lines with best price
var noOfRowsUpdated = await jsstoreCon.update({
    in: 'orderLine',
    set: {
        lineAmount: 0
    },
    mapSet: 'lineAmountMapSet.mapSet',
    where: {
        cartId: orderId,
        itemNumber: item.itemNumber
    }
});
console.log(`data updated ${noOfRowsUpdated}`);

**Comment by ujjwalguptaofficial** [comment]
If you are using jsstore - you will have to use `importScripts` to import your scripts . I have also updated doc.

and if runing without web worker, you can directly use the method. Have a look at doc - https://jsstore.net/tutorial/update/map-set/#withoutwebworker

**Comment by 10787** [comment]
I guess I am using worker then, but I must admit I never fully understood the difference between with or without worker. I am working with a cloud application, so I don't have the option of saving a .js file for import, so probably my only chance is to remove the worker. Not sure if that will affect the code I already has been writing, but what are the biggest downsides of not using worker?

**Comment by ujjwalguptaofficial** [comment]
By using worker - all jsstore code are executed in a seperate thread using web worker, so even if some queries are CPU intensive - they won't affect your UI (any animation or other code). 

But when using without worker - code run in main thread, so you might see some slowness in your app but doesn't happen most of the time.

I hope this gives you good idea about worker and without worker.

@10787 i think its possible to add js file in your app too. Do you have images or any assets in your app ? Just like images you can add a js file (treat them like an asset for now) and pass the path in `importScript`
