### ISSUE TITLE
Multiple condition in where not working

### ISSUE THREAD

**Issue by kamalakkanni** [ujjwalguptaofficial/JsStore#31]
Hi,

Below is my select query

 ```
 return this._connection.select({
            From: this._indexedDBLiveDBArticleTableName,
            Where: {
              
                Url:{'!=':url},
                CustomSection: section
            },
            Limit: this._Count,
            
       
          
            
        });

``` 
In where clause ,I am checking 2 conditions .only one is working.another is not working

**Comment by kamalakkanni** [comment]
I got duplicate data that's y I referred your tutorial

http://jsstore.net/tutorial/distinct

*Note :- *If you want to return the distinct results based on some columns,
then you should use GroupBy.

-Here I have to fetch data based on 2 conditions only.one is url!=url and
CustomSection=section..If url!=url is worked means CustomSection=section
not working and vice versa.If both condition worked means I don't need
distinct also

**Comment by ujjwalguptaofficial** [comment]
Can you check whether - section or url passed is null ?

**Comment by kamalakkanni** [comment]
I checked those value both not has null value

**Comment by ujjwalguptaofficial** [comment]
I cant help you here, since I cant reporoduce this at my side. I have tried with different query at my side and all worked well.

Though i am not saying that you are wrong. It may be somewhere where it is failing.

Can you give me some url, where i can debug or something like that. Or you can try our example and try to produce wrong result and send me a screenshot.

Thanks

**Comment by kamalakkanni** [comment]
ok.Thanks
