### ISSUE TITLE
GroupBy shows ungrouped fields

### ISSUE THREAD

**Issue by Mc128k** [ujjwalguptaofficial/JsStore#37]
This is a minor issue, but it creates something incoherent. If I group by a field, the other fields are shown too, and this doesn't make sense as we don't really care to get unique fields if we are grouping them. SQL would complain that ungrouped fields must be part of an aggregation function (I think) or be equal.

Please tell me if you need some examples, it might be not perfectly clear.

**Comment by ujjwalguptaofficial** [comment]
Actually indexeddb is NoSQL database technology, so it stores the whole object. So jsstore gives output what is saved inside the db. We can actually remove the unwanted columns but jsstore does not do this -because it would take some extra time and resources.

I understand this is little different for sql users. Lets understand this by an example - Consider we have a box which contains - pen, pencil, ball etc. In sql when you save data - every item of box is saved into another box which will contains the same item but in nosql the whole box will be saved irrespective of what is inside the box. Now when we will select data - its easier for sql to get some particular item but in nosql it would take some time and resource. So its better to select what is saved that is whole box and retrieve what you want from the box. 

Hope you are able to understand that. I have made this completely basics, so that everybody can understand what is best and why.

Thanks
