### ISSUE TITLE
Where condition is not working in Chrome .Can you please check?

### ISSUE THREAD

**Issue by paragpadsumbiya** [ujjwalguptaofficial/JsStore#56]
Thanks Mate for awesome plugin.But where condition is not working in google chrome browser can you please check and update this.

**Comment by ujjwalguptaofficial** [comment]
You are welcome buddy. Could you tell me what is the query you are passing.
Please paste the whole query.

On 06-Jul-2018 3:25 PM, "Parag Padsumbiya" <notifications@github.com> wrote:

Thanks Mate for awesome plugin.But where condition is not working in google
chrome browser can you please check and update this.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/ujjwalguptaofficial/JsStore/issues/56>, or mute the
thread

**Comment by paragpadsumbiya** [comment]
@ujjwalguptaofficial I figure it out .Everything was working fine with firefox as Firefox trimmed passed value in query and remove white spaces where chrome was not trimmed value thats why it was returned empty data .So passing value by trimming it is working fine.
