### ISSUE TITLE
Table refresh with new columns

### ISSUE THREAD

**Issue by gujral87** [ujjwalguptaofficial/JsStore#65]
Hi, 

Is there a way to refresh table with new columns?  say I've name, age as column for now & after adding few data, I would like to add new column email & just refresh table design and it add default null value on all rows. 

Hope I explained it correctly.  Thanks for the help.

**Comment by ujjwalguptaofficial** [comment]
Yeah I got you. You can achieve the above scenario but due to the limitation of indexeddb - all data from a particular table will be deleted. To overcome this situation - you can select all data and assign to a variable and when table schema is recreated, you can reinsert those data.

check out change table schema doc - http://jsstore.net/tutorial/change-table-design/

I have also created an example for demonstrating this -  https://github.com/ujjwalguptaofficial/JsStore/tree/master/examples/change%20table%20schema

**Comment by gujral87** [comment]
Thanks Ujjwal. I've faced anything issue as well. I've raised it, please look into it as well.

Cheers!
