### ISSUE TITLE
can't working properly in web worker

### ISSUE THREAD

**Issue by f5cs** [ujjwalguptaofficial/JsStore#81]
This is the best indexeddb framework I have know！I have try it in web work,when i found it can't working properly in web worker,maybe the self.postMessage to the window.
My worker.js code is as follows:

importScripts('hcwallet.js', 'jsstore.js','jsstore.worker.min.js','txTool.js');
bipTools = require('hcWallet');
hcdb=new JsStore.Instance();
hcdb.isDbExist('xLeadge_busi_cfg').then(function (isExist) {
    hcdb.openDb('xLeadge_busi_cfg').then(function () {
         **cant't execute here!**
    });
}).catch(function (err) {
    console.log(err);
});

**Comment by f5cs** [comment]
In order to avoid affecting the smoothness of the ui operation, i have many socket message to process (include save the message to indexeddb) within web worker.

**Comment by ujjwalguptaofficial** [comment]
You are able to execute isDbExist but not openDb ?

**Comment by ujjwalguptaofficial** [comment]
Make sure you have created db. Not sure but seems like you are not creating database & trying to open it.  

Turn on the log for knowing query flow. Hope this helps.

**Comment by f5cs** [comment]
Hi,ujjwalguptaofficial！
Thank you for your response
I have created the database and it works fine in the window.
Just when I put it in the worker, there will be problems.
Can execute any jsstore logic, but  all of them have nothing happens,even no error message!

**Comment by f5cs** [comment]
I have debugge the JsStore code:
    QueryExecutor.prototype.returnResult_ = function (result) {
        if (_config__WEBPACK_IMPORTED_MODULE_3__["Config"].isRuningInWorker === true) {
            it execute to here,  why isRuningInWorker === true? i have use  use it within no worker:hcdb=new JsStore.Instance();
            **### self.postMessage(result);**
        }
        else {
            this.onQueryFinished(result);
        }
    };

**Comment by f5cs** [comment]
now i have resovle the problem by the following:
in my worker.js, set the variable before importScripts:
**ServiceWorkerGlobalScope=true;**
importScripts('hcwallet.js','jsstore.worker.js', 'jsstore.js','txTool.js');

so,when the jsstore.worker.js execute,can't set the variable _config__WEBPACK_IMPORTED_MODULE_3__["Config"].isRuningInWorker = true,
then result return not postMessage to window,but do onQueryFinished function,
it's working fine.

var initialize = function () {
    if (typeof self.alert === 'undefined' && typeof ServiceWorkerGlobalScope === 'undefined') {
        **_config__WEBPACK_IMPORTED_MODULE_3__["Config"].isRuningInWorker = true;**
        self.onmessage = function (e) {
            log("Request executing from WebWorker, request name: " + e.data.name);
            new _query_executor__WEBPACK_IMPORTED_MODULE_2__["QueryExecutor"]().checkConnectionAndExecuteLogic(e.data);
        };
    }
};
initialize();

**Comment by ujjwalguptaofficial** [comment]
Hey there - I looked into your further comments & found that this is not handled by our side, since we directly support web worker without any configuration from user but in your situation you want to control the web worker flow by urself.

What happens is that - when jsstore detects its executed inside the workerscope, it implements worker.onmessage & thus the problem for ur case ,since you want to handle this by urself. 

I have exposed the config which controls the worker functionality. Please download version - 2.8.1 & write the below code after scripts has been downloaded.

```
JsStoreWorker.Config.isRuningInWorker=false;
```

Hope i am clear & this helps. Let me know please.

**Comment by f5cs** [comment]
in web worker,there a little bug that jsstore detects its executed inside the workerscope,it still postMessage to window without set isRuningInWorker=false manually.
my browser is chrome, u r use the firefox?
by the way, "JsStoreWorker.Config.isRuningInWorker=false;" it much better and works normally.

**Comment by ujjwalguptaofficial** [comment]
Yes this is because its normal behavior is to run inside a worker & if it detects its not inside the worker then it won't use self.postMessage . The flow is executed based on the flag - Config.isRuningInWorker.

This is the reason, I have exposed this to user. so that they can control this manually.
